import { describe, expect, it } from 'vitest'
import {
  shouldIncludeMissingScenario,
  shouldOnlyGenerateMissingScenario,
  supportsMultipleValuesForIamType,
  type ExtractedConditionKey
} from './conditionKeys.js'

describe('shouldIncludeMissingScenario', () => {
  it('should not include missing scenarios for global keys declared as always present', () => {
    //Given an always-present key using IfExists
    const conditionKey: ExtractedConditionKey = {
      key: 'aws:SecureTransport',
      operators: ['BoolIfExists'],
      values: ['false'],
      paths: ['Statement.Condition.BoolIfExists.aws:SecureTransport']
    }

    //When missing scenario inclusion is checked
    const result = shouldIncludeMissingScenario(conditionKey)

    //Then no missing scenario should be generated
    expect(result).toBe(false)
  })

  it('should keep signed principal keys present for generated SCP requests', () => {
    //Given a signed-principal key used in an SCP request model
    const conditionKey: ExtractedConditionKey = {
      key: 'aws:PrincipalArn',
      operators: ['ArnEquals'],
      values: ['arn:aws:iam::111111111111:role/TestRole'],
      paths: ['Statement.Condition.ArnEquals.aws:PrincipalArn']
    }

    //When missing scenario inclusion is checked for SCP
    const result = shouldIncludeMissingScenario(conditionKey, {
      policyType: 'scp',
      requestModel: 'generatedSignedScpRequest',
      action: 's3:GetObject',
      resource: 'arn:aws:s3:::example-bucket/example.txt'
    })

    //Then generated signed SCP requests should keep the key present
    expect(result).toBe(false)
  })

  it.each(['aws:PrincipalAccount', 'aws:PrincipalArn', 'aws:PrincipalOrgID', 'aws:userid'])(
    'should include missing scenarios for %s in generated RCP requests',
    (key) => {
      //Given a principal-related key used in an RCP request model
      const conditionKey: ExtractedConditionKey = {
        key,
        operators: ['StringEqualsIfExists'],
        values: ['cloud-copilot-example-value'],
        paths: [`Statement.Condition.StringEqualsIfExists.${key}`]
      }

      //When missing scenario inclusion is checked for RCP
      const result = shouldIncludeMissingScenario(conditionKey, {
        policyType: 'rcp',
        requestModel: 'generatedSignedRcpRequest',
        action: 's3:GetObject',
        resource: 'arn:aws:s3:::example-bucket/example.txt'
      })

      //Then RCP scenarios should include anonymous or otherwise absent principal context
      expect(result).toBe(true)
    }
  )

  it('should include missing scenarios by default for keys without maintained metadata', () => {
    //Given a global key without maintained presence metadata
    const conditionKey: ExtractedConditionKey = {
      key: 'aws:ResourceOrgID',
      operators: ['StringEquals'],
      values: ['o-example'],
      paths: ['Statement.Condition.StringEquals.aws:ResourceOrgID']
    }

    //When missing scenario inclusion is checked
    const result = shouldIncludeMissingScenario(conditionKey)

    //Then a missing scenario should be generated by default
    expect(result).toBe(true)
  })

  it.each([
    { key: 'aws:ResourceAccount', includeMissing: false },
    { key: 'aws:ResourceOrgID', includeMissing: true },
    { key: 'aws:ResourceOrgPaths', includeMissing: true }
  ])(
    'should set supported generated RCP missing scenario availability for $key',
    ({ key, includeMissing }) => {
      //Given a resource-info key in a supported RCP action
      const conditionKey: ExtractedConditionKey = {
        key,
        operators: ['StringEquals'],
        values: ['cloud-copilot-example-value'],
        paths: [`Statement.Condition.StringEquals.${key}`]
      }

      //When missing scenario inclusion is checked for RCP
      const result = shouldIncludeMissingScenario(conditionKey, {
        policyType: 'rcp',
        requestModel: 'generatedSignedRcpRequest',
        action: 's3:GetObject',
        resource: 'arn:aws:s3:::example-bucket/example.txt'
      })

      //Then ResourceAccount is present-only, while organization keys may be absent
      expect(result).toBe(includeMissing)
    }
  )
})

describe('shouldOnlyGenerateMissingScenario', () => {
  it.each([
    'aws:SourceAccount',
    'aws:SourceArn',
    'aws:SourceOwner',
    'aws:SourceOrgID',
    'aws:SourceOrgPaths'
  ])('should identify %s as only absent in generated SCP requests', (key) => {
    //Given a key that cannot be present in the generated SCP request model
    const conditionKey: ExtractedConditionKey = {
      key,
      operators: ['StringEqualsIfExists'],
      values: ['111111111111'],
      paths: [`Statement.Condition.StringEqualsIfExists.${key}`]
    }

    //When missing-only scenario generation is checked
    const result = shouldOnlyGenerateMissingScenario(conditionKey)

    //Then only the missing-key scenario should be generated
    expect(result).toBe(true)
  })

  it.each(['aws:SourceAccount', 'aws:SourceArn', 'aws:SourceOwner', 'aws:SourceOrgID'])(
    'should not use SCP missing-only metadata for %s in generated RCP requests',
    (key) => {
      //Given a source key in an RCP request model
      const conditionKey: ExtractedConditionKey = {
        key,
        operators: ['StringEqualsIfExists'],
        values: ['111111111111'],
        paths: [`Statement.Condition.StringEqualsIfExists.${key}`]
      }

      //When missing-only scenario generation is checked for RCP
      const result = shouldOnlyGenerateMissingScenario(conditionKey, {
        policyType: 'rcp',
        requestModel: 'generatedSignedRcpRequest',
        action: 's3:GetObject',
        resource: 'arn:aws:s3:::example-bucket/example.txt'
      })

      //Then present values should still be generated for RCPs
      expect(result).toBe(false)
    }
  )

  it.each(['aws:ResourceAccount', 'aws:ResourceOrgID', 'aws:ResourceOrgPaths'])(
    'should only generate missing scenarios for %s when RCP action lacks resource-info keys',
    (key) => {
      //Given a resource-info key in an excluded RCP action
      const conditionKey: ExtractedConditionKey = {
        key,
        operators: ['StringEqualsIfExists'],
        values: ['111111111111'],
        paths: [`Statement.Condition.StringEqualsIfExists.${key}`]
      }

      //When missing-only scenario generation is checked for RCP
      const result = shouldOnlyGenerateMissingScenario(conditionKey, {
        policyType: 'rcp',
        requestModel: 'generatedSignedRcpRequest',
        action: 'ec2:CopySnapshot',
        resource: '*'
      })

      //Then only missing scenarios should be generated
      expect(result).toBe(true)
    }
  )
})

describe('supportsMultipleValuesForIamType', () => {
  it('should identify ArrayOf types as supporting multiple request-context values', () => {
    //Given IAM condition-key type names
    const arrayType = 'ArrayOfString'
    const scalarType = 'String'

    //When multivalue support is checked
    const arrayResult = supportsMultipleValuesForIamType(arrayType)
    const scalarResult = supportsMultipleValuesForIamType(scalarType)

    //Then only ArrayOf types should support multiple values
    expect(arrayResult).toBe(true)
    expect(scalarResult).toBe(false)
  })
})
